### ISSUE TITLE
couldn't find "libjndcrash.so

### ISSUE THREAD

**Issue by RomanDorofeyev** [ivanarh/jndcrash#1]
I'm trying to use jndcrash in my module but faced some issue when run application. It is more like building issue but anyway may be you coud give a hint how to solve it.

When using standart `implementation ` then gradle does not includ any jndcrash files into build so I must  put aar file to my libs folder `implementation files("libs/jndcrash-libunwind-0.8.aar")`

After building my module as aar library I can see jndcrash files included but I'm getting runtime exception : 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brandio.androidsample, PID: 17834
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.brandio.androidsample-SmjaZPIMVek_HLrynOlY5w==/base.apk"],nativeLibraryDirectories=[/data/app/com.brandio.androidsample-SmjaZPIMVek_HLrynOlY5w==/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libjndcrash.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at ru.ivanarh.jndcrash.NDCrash.<clinit>(SourceFile:197)
        at ru.ivanarh.jndcrash.NDCrash.initializeOutOfProcess(SourceFile:56)
        at com.brandio.ads.Controller.a(SourceFile:260)
        at com.brandio.ads.Controller.f(SourceFile:58)
        at com.brandio.ads.Controller$3.onSuccessResponse(SourceFile:362)
        at com.brandio.ads.ServiceClient$3.a(SourceFile:330)
        at com.brandio.ads.ServiceClient$3.onPostExecute(SourceFile:313)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
However I can see the missed  "libjndcrash.so" inside build https://prnt.sc/t63ve8
But looks like the correct structure missed during building or it requires some other installation.

May be any suggestion how to solve it?

**Comment by ivanarh** [comment]
> https://prnt.sc/t63ve8

Is it a screenshot of APK file contents?
I suspect no. In order to find a reason of this problem please inspect contents of output APK file, make sure that the library exists for an architecture that you are running on.
If it doesn't exists a problem is 100% with your build system, in this case I would recommend to pay inspect build.gradle file, check that abifilters doesn't exclude a library from output apk.
